### ISSUE TITLE
very nice!  but about begin()...

### ISSUE THREAD

**Issue by fschwiet** [joshuaclayton/specit#1]
I've been using QUnit for a bit, I just ran across SpecIt on the QUnit site.  It looks nice!  I've only started.

  I did have one comment though.  I noticed begin() is required for initialization.  Could you consider making it optional?  NUnit has a similar "SetUp" attribute, but according to Martin Fowler thats not the ideal (http://xunitpatterns.com/There%20is%20Always%20an%20Exception.html).

  It seems its easier to initialize per-test variables with:

```
var globalIndex = 0;
var firstActual = {};
var secondActual = {};

describe("should only specify initialization once", function () {

    var uniqueIndex = globalIndex++;

    it("uniqueIndex is unique once", function () {

        firstActual = uniqueIndex;

        firstActual.shouldNot(eql, secondActual);
    });

    it("uniqueIndex is unique twice", function () {

        secondActual = uniqueIndex;

        firstActual.shouldNot(eql, secondActual);
    });
});
```

instead of:

```
var globalIndex = 0;
var firstActual = {};
var secondActual = {};

describe("can allow before initialization once", function () {

    var uniqueIndex;

    before(function () {
        uniqueIndex = globalIndex++;
    });

    it("uniqueIndex is unique once", function () {

        firstActual = uniqueIndex;

        firstActual.shouldNot(eql, secondActual);
    });

    it("uniqueIndex is unique twice", function () {

        secondActual = uniqueIndex;

        firstActual.shouldNot(eql, secondActual);
    });
});
```

**Comment by joshuaclayton** [comment]
Hey,

It's nice to see some interest in specit!  I'm guessing you're referring to `before` and not `begin` - if I misunderstood, sorry!

`begin` isn't required within a `describe` block, just available as a setup (as you mentioned) for each test.  For each `it`, it doesn't look like it would rerun any code, which isn't ideal for many people.

As a reminder, this is a wrapper on QUnit's functionality, which natively supports test setups and something I definitely want to have available.

**Comment by fschwiet** [comment]
Yes.  Sorry I fixed the content last night but notice I'd left the title in error.  I'm going to close this out by priority.
