### ISSUE TITLE
jQuery.find('.class') broken on IE after including SpecIt

### ISSUE THREAD

**Issue by fschwiet** [joshuaclayton/specit#2]
I found something weird...  I get an incorrect result if I use a jquery selector with a css class.  jQuery is choking on member 'shouldNot' when doing a for loop.  To repro:

Open SpecIt's test.html

Paste the following into the address bar:

```
javascript:alert($("<div><a class='edit-link'>edit</a></div>").find("a.edit-link").length);
```

On Firefox, the expected result happens.  That is, an alert box opens with value '1'.

On Internet Explorer 8, an exception is thrown.

**Comment by fschwiet** [comment]
Chrome behaves like Firefox (it works, alert box opens with '1')

**Comment by joshuaclayton** [comment]
What's the exception?

Also, can you run `javascript:alert(1);` in the address bar and report back as to what IE8 does? Thanks!

**Comment by fschwiet** [comment]
I apologize I don't recall, I may have just been learning.  For javascript testing I have been using jasmine bdd, similar to SpecIt.
