### ISSUE TITLE
Doesn't work correctly with latest qunit

### ISSUE THREAD

**Issue by juamei** [joshuaclayton/specit#3]
QUnit has added a QUnit.diff function since specit was originally written which dies on equality comparisons when using specit. This due to missing parameters on nativeShould and nativeShouldNot which have been added to the prototype of Object by specit.

There is also an issue if those prototype assignments are removed and a secondary function is created to replace the actual.should( comparison, expected ) construct with expected( actual, should, comparison, expected ). The qunit equal test now works but on a pass returns the appended fail string eg "expect "blah", result "blah", dif... ". 
This is due to the casting of string literals to String objects by use of call and apply in specit which causes a secondary equality check within qunit to fail and hence append the fail message to a passing test.

**Comment by joshuaclayton** [comment]
Add an assert method, which wraps getting a value.
- This allows for the removal of all the should/shouldNot pollution on
  various prototypes.
- This fixes issues with the latest version of qunit
- Closed by b5e61cbfe4c0ea4eb3bd9f38be402a289af55daf
