### ISSUE TITLE
Creating an asynchronous test

### ISSUE THREAD

**Issue by robdmoore** [joshuaclayton/specit#7]
What are your thoughts on a syntax for specifying an asynchronous test?

**Comment by joshuaclayton** [comment]
Rob, this is actually already implemented as `asyncIt` (instead of just `it`) and uses qunit's implementation of `asyncTest`.

**Comment by robdmoore** [comment]
Excellent! Thanks for letting me know.

Perhaps you might want to add it to the documentation on the homepage for specit?

**Comment by joshuaclayton** [comment]
Done; thanks!
